apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: abdou1tabib/client:0.0.1
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: abdou1tabib/comments:0.0.1
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: abdou1tabib/event-bus:0.0.1
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: abdou1tabib/moderation:0.0.1
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: abdou1tabib/posts:0.0.1
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: abdou1tabib/query:0.0.1
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
